displayName: Captcha Protect
summary: Add an anti-bot challenge to protected routes
type: middleware
import: github.com/tracyhatemice/captcha-protect
testData:
  ProtectRoutes: /
  ChallengeTmpl: challenge.tmpl.html
  Window: 86400
  IPForwardedHeader: "X-Forwarded-For"
  CaptchaProvider: turnstile
  SiteKey: 1x00000000000000000000AA
  SecretKey: 1x0000000000000000000000000000000AA
